services:
#
  bazarr:
    image: ghcr.io/linuxserver/bazarr:development
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:bazarr
      - TP_THEME=plex
    volumes:
      - ${DOCK}/bazarr:/config
      - ${MEDIA}/Movies:/movies
      - ${MEDIA}/TV:/tv
    ports:
      - 9010:6767
    restart: unless-stopped
    networks:
      - media

#
  gluetun:
    image: qmcgaw/gluetun
    #~ image: qmcgaw/gluetun:1243
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 9005:7878     # Radarr
      - 9012:8686     # Lidarr
      - 9006:9091     # Trans web
      - 51413:51413   # Trans
      - 9003:8989     # Sonarr
      - 9004:9696     # Prowlarr
    volumes:
      - ${DOCK}/gluetun:/gluetun
      - ${DOCK}/gluetun/port:/tmp/gluetun/
    environment:
      - OPENVPN_USER=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - VPN_SERVICE_PROVIDER=private internet access
      - TZ=${TZ}
      - SERVER_REGIONS=${VPN_CONFIG}
      - PUID=${PUID}
      - PGID=${PGID}
      - FIREWALL_OUTBOUND_SUBNETS=10.10.10.0/24,10.10.20.0/24,10.10.30.0/24
      - OPENVPN_CIPHERS=aes-256-gcm
      - OPENVPN_AUTH=sha256
      - PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET=strong
      - PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING=on
    restart: always
    networks:
      - media

#
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCK}/heimdall:/config
    ports:
      - 9000:80
      - 9997:443
    restart: unless-stopped
    networks:
      - media

#
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    runtime: nvidia
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - ${DOCK}/jellyfin:/config
      - ${MEDIA}:/media
      - /tmp/jf:/transcode
      - ${DOCK}/jellyfin/cache:/cache
    ports:
      - 9009:8096
    restart: unless-stopped
    networks:
      - media

#
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=plex
    volumes:
      - ${DOCK}/lidarr:/config
      - ${MEDIA}/nMusic:/music
      - ${DL}:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

#
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCK}/nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - media

#
  ombi:
    image: ghcr.io/linuxserver/ombi:development
    container_name: ombi
    mem_limit: 1G
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - BASE_URL=/ombi
    volumes:
      - ${DOCK}/ombi:/config
    ports:
      - 9002:3579
    restart: unless-stopped
    networks:
      - media

#
  plexms:
    container_name: plexms
    restart: always
    image: plexinc/pms-docker:latest
    runtime: nvidia
    volumes:
      - ${DOCK}/plexms/config:/config
      - /tmp:/transcode
      - ${MEDIA}:/media
      - ${DOCK}/plexms/shared:/shared
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      #~ - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TZ}
      - HOSTNAME=Ash Plex
      - PLEX_CLAIM=${PLEXC}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP=http://10.10.10.8:32400/
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    restart: unless-stopped
    networks:
      - media

#
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
     # - PASSWORD=password     ## Uncomment to enable basic authentication, username = podgrab
    volumes:
      - ${DOCK}/podgrab:/config
      - ${MEDIA}/Podcasts:/assets
    ports:
      - 9008:8080
    restart: unless-stopped
    networks:
      - media

#
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=plex
    volumes:
      - ${DOCK}/prowlarr:/config
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

#
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=plex
    volumes:
      - ${DOCK}/radarr:/config
      - ${MEDIA}/Movies:/movies
      - ${DL}:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

#
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=plex
    volumes:
      - ${DOCK}/sonarr:/config
      - ${MEDIA}/TV:/tv
      - ${DL}:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

#
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    network_mode: service:gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:transmission
      - TP_THEME=plex
      - PEERPORT=${VPN_PORT}
    volumes:
      - ${DOCK}/transmission:/config
      - ${DL}:/downloads
      - ${DOCK}/transmission/watch:/watch
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

networks:
  media:
    name: media_net
