services:
  unifiApp:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifiApp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MONGO_USER=${MONGOUSER}
      - MONGO_PASS=${MONGOPWD}
      - MONGO_HOST=mongo-unifi
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi-db
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - ${DOCK}/unifiApp:/config
    ports:
      - 9007:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
    restart: unless-stopped
    networks:
      - unifi

#
  mongo:
    image: mongo:4.4
    restart: always
    container_name: mongo-unifi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 27017:27017
    volumes:
      - ${DOCK}/mongo:/data/db
      #~ - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - unifi

networks:
  unifi:
    name: unifi_net
